# Generated by Django 5.0.6 on 2024-08-01 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('startingbid', models.IntegerField()),
                ('currentprice', models.IntegerField()),
                ('bidders', models.ManyToManyField(blank=True, related_name='buyingitems', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellingitems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
